#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = boostDemoBind

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    boostBindDemo.h \
    boostBindDemoDefind.h \
    boostDemoBindList.h

SOURCES += \
    boostBindDemo.cpp \
    boostDemoBindList.cpp \
    main.cpp
