#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = Template

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    AbstractClass.h \
    ConcreteClassA.h \
    ConcreteClassB.h

SOURCES += \
    AbstractClass.cpp \
    ConcreteClassA.cpp \
    ConcreteClassB.cpp \
    main.cpp
