#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = vsprintf

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    PrintfLog.h \
    Log.h

SOURCES += \
    PrintfLog.cpp \
    main.cpp \
    Log.cpp
