#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = Conversion

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

SOURCES += \
    conversion.cpp

HEADERS += \
    conversiontest.h
