#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = atomic
QMAKE_CXXFLAGS += -std=c++11
SOURCES *= \
    ./main.cpp

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
