#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = Builder

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    Product.h \
    ConcreteBuilder.h \
    Director.h \
    Builder.h \
    ConcreteBuilder1.h

SOURCES += \
    Product.cpp \
    ConcreteBuilder.cpp \
    ConcreteBuilder1.cpp \
    Director.cpp \
    Client.cpp
