#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = Prototype

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    ProtoType.h \
    ConcretePrototype.h

SOURCES += \
    ConcretePrototype.cpp \
    main.cpp \
    ProtoType.cpp
