#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = Adapter

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    Target.h \
    Adaptee.h \
    Adapter.h \
    ClassAdapter.h

SOURCES += \
    Adapter.cpp \
    Adaptee.cpp \
    Target.cpp \
    Client.cpp \
    ClassAdapter.cpp
