#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = AbstractFactory

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    AbstractFactory.h \
    ConcreteFactory1.h \
    ConcreteFactory2.h \
    AbstractProductA.h \
    AbstractProductB.h \
    ProductA1.h \
    ProductA2.h \
    ProductB1.h \
    ProductB2.h

SOURCES += \
    AbstractFactory.cpp \
    AbstractProductA.cpp \
    AbstractProductB.cpp \
    ConcreteFactory1.cpp \
    ConcreteFactory2.cpp \
    main.cpp \
    ProductA1.cpp \
    ProductA2.cpp \
    ProductB1.cpp \
    ProductB2.cpp
