#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = QTC++Test

SOURCES *= \
    ./Service.cpp \
    ./main.cpp \
    CommunicationClass.cpp \
    TransferPython.cpp

HEADERS *= \
    ./Service.h \
    CommunicationClass.h \
    TransferPython.h \
    ProjectDef.h

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

LIBS += -L /usr/include/python2.7 -lpython2.7
