#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = signal
QMAKE_CXXFLAGS += -std=c++0x

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    Signal/Signal.h \
    Signal/SignalPublicIF.h \
    Receiver/SignalReceiver.h
