#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = Audition
QMAKE_CXXFLAGS += -std=c++0x

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    BinaryTree.h

SOURCES += \
    main.cpp
