#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = events
QMAKE_CXXFLAGS += -std=c++0x

PATHS *= \
    . \
    ./system \
    ./socketBase \
    ./socket

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    socketBase/SocketImpl_ZMQ.h \
    socketBase/AbstractSocket.h \
    socketBase/AbstractDataBlock.h \
    socket/Socket.h \
    socket/EV_Socket.h \
    socket/Events_Context.h \
    socket/EV_Sync.h \
    socket/Config.h \
    system/EventSender.h \
    system/EV_ChannelFactory.h \
    socket/SocketContext.h \
    system/EventReceiver.h \
    system/EventReceiverImpl.h \
    system/EventSystem.h

SOURCES += \
    socketBase/SocketImpl_ZMQ.cpp \
    socket/Socket.cpp \
    socket/EV_Socket.cpp \
    socket/Events_Context.cpp \
    socket/EV_Sync.cpp \
    main.cpp \
    system/EventSender.cpp \
    system/EV_ChannelFactory.cpp \
    socket/SocketContext.cpp \
    system/EventReceiver.cpp \
    system/EventReceiverImpl.cpp \
    system/EventSystem.cpp

unix:!macx: LIBS += -L$$PWD/../../../../../../usr/lib/ -lzmq

INCLUDEPATH += $$PWD/../../../../../../usr/include
DEPENDPATH += $$PWD/../../../../../../usr/include
