#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = XmlTest
QT += qml quick xml
SOURCES *= \
    ./Test.cpp \
    ./VRConst.cpp \
    ./VRXMLStrParse.cpp \
    DemoItem.cpp \
    VoiceVoiceRecogListItemBase.cpp

HEADERS *= \
    ./VRConst.h \
    ./VRXMLStrParse.h \
    ./VoiceVoiceRecogDef.h \
    ./VoiceVoiceRecogModelDef.h \
    DemoItem.h \
    VoiceVoiceRecogListItemBase.h

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
