#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = point

SOURCES *= \
    ./point.cpp \

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
