#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = Iterator

SOURCES *= \
    ./ConcreteAggregate.cpp \
    ./ConcreteIterator.cpp \
    ./main.cpp \
    Aggregate.cpp \
    Iterator.cpp

HEADERS *= \
    ./Aggregate.h \
    ./ConcreteAggregate.h \
    ./ConcreteIterator.h \
    ./Iterator.h

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
