#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = C++AndPython

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

SOURCES += \
    test.cpp

LIBS += -L /usr/include/python2.7 -lpython2.7
