#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = snake_game

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    Painting.h \
    timer.h \
    snakeMoving.h

SOURCES += \
    Painting.cpp \
    timer.cpp \
    snakeMoving.cpp
