#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = ProcessSend

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    NGTestService.h \
    NGTestDef.h

SOURCES += \
    NGTestService.cpp \
    main.cpp
