#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = DesignModel

SOURCES *= \
    ./AbstractFactory/AbstractFactory.cpp \
    ./AbstractFactory/AbstractProductA.cpp \
    ./AbstractFactory/AbstractProductB.cpp \
    ./AbstractFactory/ConcreteFactory1.cpp \
    ./AbstractFactory/ConcreteFactory2.cpp \
    ./AbstractFactory/ProductA1.cpp \
    ./AbstractFactory/ProductA2.cpp \
    ./AbstractFactory/ProductB1.cpp \
    ./AbstractFactory/ProductB2.cpp \
    ./AbstractFactory/main.cpp \
    ./Adapter/Adaptee.cpp \
    ./Adapter/Adapter.cpp \
    ./Adapter/ClassAdapter.cpp \
    ./Adapter/Client.cpp \
    ./Adapter/Target.cpp \
    ./Bridge/ConcreteAbstractionA.cpp \
    ./Bridge/ConcreteAbstractionB.cpp \
    ./Bridge/ConcreteAbstractionImplA.cpp \
    ./Bridge/ConcreteAbstractionImplB.cpp \
    ./Bridge/main.cpp \
    ./Builder/Client.cpp \
    ./Builder/ConcreteBuilder.cpp \
    ./Builder/ConcreteBuilder1.cpp \
    ./Builder/Director.cpp \
    ./Builder/Product.cpp \
    ./FactoryModel/ConcreteFactory.cpp \
    ./FactoryModel/ConcreteProduct1.cpp \
    ./FactoryModel/ConcreteProduct2.cpp \
    ./FactoryModel/Factory.cpp \
    ./FactoryModel/Product.cpp \
    ./FactoryModel/main.cpp \
    ./Observer/ConcreteObserver.cpp \
    ./Observer/ConcreteObserver1.cpp \
    ./Observer/ConcreteSubject.cpp \
    ./Observer/Observer.cpp \
    ./Observer/Subject.cpp \
    ./Observer/main.cpp \
    ./Prototype/ConcretePrototype.cpp \
    ./Prototype/ProtoType.cpp \
    ./Prototype/main.cpp \
    ./Proxy/BigImage.cpp \
    ./Proxy/BigImageProxy.cpp \
    ./Proxy/Image.cpp \
    ./Proxy/main.cpp \
    ./Singleton/Singleton.cpp \
    ./Singleton/main.cpp \
    ./Template/AbstractClass.cpp \
    ./Template/ConcreteClassA.cpp \
    ./Template/ConcreteClassB.cpp \
    ./Template/main.cpp

HEADERS *= \
    ./AbstractFactory/AbstractFactory.h \
    ./AbstractFactory/AbstractProductA.h \
    ./AbstractFactory/AbstractProductB.h \
    ./AbstractFactory/ConcreteFactory1.h \
    ./AbstractFactory/ConcreteFactory2.h \
    ./AbstractFactory/ProductA1.h \
    ./AbstractFactory/ProductA2.h \
    ./AbstractFactory/ProductB1.h \
    ./AbstractFactory/ProductB2.h \
    ./Adapter/Adaptee.h \
    ./Adapter/Adapter.h \
    ./Adapter/ClassAdapter.h \
    ./Adapter/Target.h \
    ./Bridge/Abstraction.h \
    ./Bridge/AbstractionImpl.h \
    ./Bridge/ConcreteAbstractionA.h \
    ./Bridge/ConcreteAbstractionB.h \
    ./Bridge/ConcreteAbstractionImplA.h \
    ./Bridge/ConcreteAbstractionImplB.h \
    ./Builder/Builder.h \
    ./Builder/Client.h \
    ./Builder/ConcreteBuilder.h \
    ./Builder/ConcreteBuilder1.h \
    ./Builder/Director.h \
    ./Builder/Product.h \
    ./FactoryModel/ConcreteFactory.h \
    ./FactoryModel/ConcreteProduct1.h \
    ./FactoryModel/ConcreteProduct2.h \
    ./FactoryModel/Const.h \
    ./FactoryModel/Factory.h \
    ./FactoryModel/Product.h \
    ./Observer/ConcreteObserver.h \
    ./Observer/ConcreteObserver1.h \
    ./Observer/ConcreteSubject.h \
    ./Observer/Observer.h \
    ./Observer/Subject.h \
    ./Prototype/ConcretePrototype.h \
    ./Prototype/ProtoType.h \
    ./Proxy/BigImage.h \
    ./Proxy/BigImageProxy.h \
    ./Proxy/Image.h \
    ./Singleton/Singleton.h \
    ./Template/AbstractClass.h \
    ./Template/ConcreteClassA.h \
    ./Template/ConcreteClassB.h

PATHS *= \
    . \
    ./build-Observer-Desktop-Debug \
    ./AbstractFactory \
    ./Prototype \
    ./Template \
    ./build-Template-Desktop-Debug \
    ./Bridge \
    ./Adapter \
    ./FactoryModel \
    ./Observer \
    ./Builder \
    ./Proxy \
    ./build-Test-Desktop-Debug \
    ./Singleton

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
