#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = client
QMAKE_CXXFLAGS += -std=c++0x
SOURCES *= \
    ./main.cpp \
    VR_AwakeAudioToServer.cpp \
    CThread.cpp \
    MyThread.cpp

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
LIBS += -L$$PWD/../../../../../../usr/lib/ -lzmq
INCLUDEPATH += $$PWD/../../../../../../usr/lib/x86_64-linux-gnu
DEPENDPATH += $$PWD/../../../../../../usr/lib/x86_64-linux-gnu

INCLUDEPATH += $$PWD/../../../../../../usr/include
DEPENDPATH += $$PWD/../../../../../../usr/include

HEADERS += \
    VR_AwakeAudioToServer.h \
    MyThread.h \
    CThread.h

LIBS += -L$$PWD/../../../../iAuto3_Mix/out/target/product/m3muifa/system/usr/lib/ -lcurl

INCLUDEPATH += $$PWD/../../../../iAuto3_Mix/out/target/product/m3muifa/system/usr
DEPENDPATH += $$PWD/../../../../iAuto3_Mix/out/target/product/m3muifa/system/usr
