#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = FactoryModel

SOURCES *= \
    ./ConcreteFactory.cpp \
    ConcreteProduct1.cpp \
    ConcreteProduct2.cpp \
    main.cpp \
    Factory.cpp \
    Product.cpp

HEADERS *= \
    ./Product.h \
    ConcreteFactory.h \
    Factory.h \
    ConcreteProduct1.h \
    ConcreteProduct2.h \
    Const.h

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
