#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = ThreadPool
QMAKE_CXXFLAGS += -std=c++0x

PATHS *= \
    . \
    ./Demo

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    Demo/ThreadPoolDemo.h

SOURCES += \
    Demo/ThreadPoolDemo.cpp \
    main.cpp
