#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = TempCode

SOURCES *= \
    ./Temp/xxxModel.cpp

HEADERS *= \
    ./Temp/xxxModel.h

PATHS *= \
    . \
    ./Temp

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

OTHER_FILES *= \
    ./createCode.py \
    ./pyTest.py \
