#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = OA-Center
QMAKE_CXXFLAGS += -std=c++11

HEADERS *= \
    ./CurlHttp.h \
    ./LogConfig/Log_Func.h \
    ./NGVUIXMLStrParse.h \
    ./external/pugixml/* \
    ./external/curl/* \
    ./external/json/* \
    ./OA_Center.h

SOURCES *= \
    ./CurlHttp.cpp \
    ./LogConfig/Log_Func.cpp \
    ./NGVUIXMLStrParse.cpp \
    ./external/pugixml/pugixml.cpp \
    ./external/json/jsoncpp.cpp \
    ./main.cpp \
    ./OA_Center.cpp

PATHS *= \
    . \
    ./LogConfig \
    ./external \
    ./external/pugixml \
    ./external/curl \
    ./external/json \

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

LIBS += -L$$PWD/external/ -lcurl
INCLUDEPATH += $$PWD/external
DEPENDPATH += $$PWD/external

OTHER_FILES *= \
    ./OA-Center.py
