#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = Observer

SOURCES *= \
    ./ConcreteObserver.cpp \
    ./ConcreteObserver1.cpp \
    ./ConcreteSubject.cpp \
    ./Observer.cpp \
    ./main.cpp \
    Subject.cpp

HEADERS *= \
    ./ConcreteObserver.h \
    ./ConcreteObserver1.h \
    ./ConcreteSubject.h \
    ./Observer.h \
    ./Subject.h

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
