#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = Test

SOURCES *= \
    ./eunmTest.cpp

HEADERS *= \
    ./test.h

PATHS *= \
    .
QMAKE_CXXFLAGS += -std=c++0x
DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
