#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = ProcessCom

PATHS *= \
    .
QMAKE_CXXFLAGS += -std=c++0x
DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    NGTestServiceStub.h \
    replier.h \
    NGTestDef.h \
    NGTestThread.h \
    NGTestPerform.h

SOURCES += \
    NGTestServiceStub.cpp \
    main.cpp \
    NGTestThread.cpp \
    NGTestPerform.cpp
