#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = LibXMLParseXML
QMAKE_CXXFLAGS += -std=c++0x

HEADERS += \
    VUIModelParseXML.h \
    VUIModelXMLDefine.h

SOURCES += \
    VUIModelParseXML.cpp \
    main.cpp

PATHS *= \
    . \
    ./../../externals/libxml2/include \
    ./../../LogConfig \
    ./../../externals/libxml2/

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

LIBS += -L$$PWD/./ -lxml2
