#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = Proxy

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    Image.h \
    BigImage.h \
    BigImageProxy.h

SOURCES += \
    Image.cpp \
    BigImage.cpp \
    BigImageProxy.cpp \
    main.cpp
