#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = pocketSphinx
QMAKE_CXXFLAGS += -std=c++11

HEADERS *= \
    ./include/cmdln_macro.h \
    ./include/config.h \
    ./include/pocketsphinx.h \
    ./include/pocketsphinx_export.h \
    ./include/ps_lattice.h \
    ./include/ps_mllr.h \
    ./include/ps_search.h \
    ./include/sphinxbase/ad.h \
    ./include/sphinxbase/agc.h \
    ./include/sphinxbase/bio.h \
    ./include/sphinxbase/bitarr.h \
    ./include/sphinxbase/bitvec.h \
    ./include/sphinxbase/byteorder.h \
    ./include/sphinxbase/case.h \
    ./include/sphinxbase/ckd_alloc.h \
    ./include/sphinxbase/clapack_lite.h \
    ./include/sphinxbase/cmd_ln.h \
    ./include/sphinxbase/cmn.h \
    ./include/sphinxbase/err.h \
    ./include/sphinxbase/f2c.h \
    ./include/sphinxbase/fe.h \
    ./include/sphinxbase/feat.h \
    ./include/sphinxbase/filename.h \
    ./include/sphinxbase/fixpoint.h \
    ./include/sphinxbase/fsg_model.h \
    ./include/sphinxbase/genrand.h \
    ./include/sphinxbase/glist.h \
    ./include/sphinxbase/hash_table.h \
    ./include/sphinxbase/heap.h \
    ./include/sphinxbase/jsgf.h \
    ./include/sphinxbase/listelem_alloc.h \
    ./include/sphinxbase/logmath.h \
    ./include/sphinxbase/matrix.h \
    ./include/sphinxbase/mmio.h \
    ./include/sphinxbase/ngram_model.h \
    ./include/sphinxbase/pio.h \
    ./include/sphinxbase/prim_type.h \
    ./include/sphinxbase/priority_queue.h \
    ./include/sphinxbase/profile.h \
    ./include/sphinxbase/sbthread.h \
    ./include/sphinxbase/sphinxbase_export.h \
    ./include/sphinxbase/strfuncs.h \
    ./include/sphinxbase/yin.h \
    ./include/sphinxbase/sphinx_config.h

SOURCES *= \
    ./src/main.cpp

PATHS *= \
    . \
    ./src \
    ./include \
    ./lib \
    ./data \
    ./include/sphinxbase \
    ./data/model \
    ./data/model/en-us \
    ./data/model/en-us/en-us

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

LIBS += -L$$PWD/lib/ -lsphinxbase
LIBS += -L$$PWD/lib/ -lpocketsphinx

INCLUDEPATH += $$PWD/include
DEPENDPATH += $$PWD/include
