#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = struct

SOURCES *= \
    ./Stack/Nested.cpp \
    ./Stack/NestedTest.cpp \
    ./Stash/LIBTEST.C \
    ./Stash/Stash.cpp \
    ./Stash/test.cpp \
    ./StashClass/Stack.cpp \
    ./StashClass/StashTest.cpp

HEADERS *= \
    ./Stack/Nested.h \
    ./Stash/Stash.h \
    ./StashClass/Stack.h

PATHS *= \
    . \
    ./StashClass \
    ./build-StashClass-Desktop-Debug \
    ./Nested \
    ./Stack \
    ./Stash

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
