#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = Smart_Pointer
QMAKE_CXXFLAGS += -std=c++0x

HEADERS *= \
    ./Simple.h \
    ./SmartPointConcrete/smartpoint.h \
    ./weakPtrTest.h

SOURCES *= \
    ./Boost_Pointer.cpp

PATHS *= \
    . \
    ./SmartPointConcrete

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS
