#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = Bridge

PATHS *= \
    .

DEPENDPATH *= $$PATHS

INCLUDEPATH *= $$PATHS

HEADERS += \
    Abstraction.h \
    AbstractionImpl.h \
    ConcreteAbstractionImplA.h \
    ConcreteAbstractionImplB.h \
    ConcreteAbstractionA.h \
    ConcreteAbstractionB.h

SOURCES += \
    ConcreteAbstractionA.cpp \
    ConcreteAbstractionB.cpp \
    ConcreteAbstractionImplA.cpp \
    ConcreteAbstractionImplB.cpp \
    main.cpp
